before_deploy:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: daegweon/ai_interview_simulator
    bucket: humanlearning-webservice-deploy
    region: ap-northeast-2
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: humanlearning-webservice-deploy
    key: latest.zip
    bundle_type: zip
    application: humanlearning
    deployment_group: humanlearning
    region: ap-northeast-2
    wait-until-deployed: true
    on: *2