language: python

python:
  - "3.6"

dist: trusty
sudo: required
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

env:
  global:
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO_VERSION=1.11.11 DB=mysql

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-numpy  
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION

before_script:
  - sudo mysql_upgrade -u root
  - mysql -u root -e 'create database if not exists humandb;'   
  - sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' identified by 'humanroot';"
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('humanroot') where User='root'; update user set plugin='mysql_native_password'; FLUSH PRIVILEGES;"
  - python manage.py makemigrations

script:
  - python manage.py migrate -v 3
  - python manage.py test -v 3

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: daegweon/ai_interview_simulator
  bucket: humanlearning-webservice-deploy
  region: ap-northeast-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: humanlearning-webservice-deploy
  key: latest.zip
  bundle_type: zip
  application: humanlearning
  deployment_group: humanlearning
  region: ap-northeast-2
  on: *2

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip